### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Olivier-Berg** [Dpbm/Dracula-DarkReader#1]
when i go to https://draculatheme.com/darkReader i get a 500 internal server error

**Comment by anthonygualandri** [comment]
Same

**Comment by hajosattila** [comment]
same

**Comment by JakubZ0** [comment]
looks like they dropped Dark Reader project, since it became 404 and it's not searchable.
Setting up Dracula manually is easy enough though, 

1. Open developer tools of Dark Reader
2. Click on Preview new design
3. Open Dark Reader again, click on "See all options", select Colors drop down and then
>you can choose Dracula under Color Scheme

I'm not 100% certain if the Color Scheme works (as of 22th March of 2023), so I suggest manual settings instead:
then set the background colour and text colour to `#282a36` and `#f8f8f2`

Hope you can use your favorite theme without hassle, have a great day! :)

**Comment by Dpbm** [comment]
Sorry about that guys. 
I've made this project some years ago, and I planed to move this repo to the official Dracula theme organization, but, unfortunately, they already had similar project. After that I forgot to update the project.

Also, the link never worked, it was just a pattern that they require for new theme implementations.

Thank you guys for helping me. Now you can see the updated version made by @jakub1812 in this repo :)
